const image_list = {
  ListPicture2URL: "images_2",
  ListPicture3URL: "images_3",
  ListPicture4URL: "images_4",
  ListPicture5URL: "images_5",
  ListPicture6URL: "images_6",
  ListPicture7URL: "images_7",
  ListPicture8URL: "images_8",
  ListPicture9URL: "images_9",
  ListPicture10URL: "images_10",
  ListPicture11URL: "images_11",
  ListPicture12URL: "images_12",
  ListPicture13URL: "images_13",
  ListPicture14URL: "images_14",
  ListPicture15URL: "images_15",
  ListPicture16URL: "images_16",
  ListPicture17URL: "images_17",
  ListPicture18URL: "images_18",
  ListPicture19URL: "images_19",
  ListPicture20URL: "images_20",
  ListPicture21URL: "images_21",
  ListPicture22URL: "images_22",
  ListPicture23URL: "images_23",
  ListPicture24URL: "images_24",
  ListPicture25URL: "images_25",
  ListPictureURL: "images_1",
};

module.exports = image_list;
